version: '3'

volumes:
  sync_storage:
    external: true

services:
  resilio_sync:
    image: resilio/sync
    hostname: resilio
    container_name: resilio
    restart: always
    ports:
     - 9999:8888
     - 55555:55555/tcp
     - 55555:55555/udp     
    volumes:
     - /mnt/data/resilio:/mnt/sync/storage     # Sync storage folder
     - ./sync.conf:/mnt/sync/sync.conf    # Configuration file
     - /mnt/data:/mnt/sync/data          # folder with data to be shared
